In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [41]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_3e8cfdebc9964cc18883a742ec3f55f4 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='15nCJ-yqVvCeb5TCiesQKlZka1YJLDav9prMAPiTRWS0',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_3e8cfdebc9964cc18883a742ec3f55f4.get_object(Bucket='crimerate-donotdelete-pr-kdlzqbku3njec1',Key='Crime rate Prediction1.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )                                                                                                                                    
dataset=pd.read_csv(body)
dataset.head()



report_year  population  robberies  robberies_percapita
0         1975      286238        819               286.13
1         1975      112478        113               100.46
2         1975      490584       3887               792.32
3         1975      116656        171               146.58
4         1975      300400        529               176.10

In [42]:
dataset

report_year  population  robberies  robberies_percapita
0            1975      286238        819               286.13
1            1975      112478        113               100.46
2            1975      490584       3887               792.32
3            1975      116656        171               146.58
4            1975      300400        529               176.10
5            1975      642154        750               116.79
6            1975      864100       9055              1047.91
7            1975      616120       7778              1262.42
8            1975      422276       2340               554.14
9            1975      262103        822               313.62
10           1975     3150000      22171               703.84
11           1975      433367       1745               402.66
12           1975      659931       7100              1075.87
13           1975      572797       2402               419.35
14           1975      864665       3386               391.60
15           1975      508140       2568               505.37
16           1975     1432444      21317              1488.16
17           1975      369000        840               227.64
18           1975      487905        433                88.75
19           1975      381275       1207               316.57
20           1975      176500        567               321.25
21           1975      705262       1050               148.88
22           1975     1372342       6422               467.96
23           1975      503411       3092               614.21
24           1975      542792       1727               318.17
25           1975      489094       3081               629.94
26           1975      249186       1345               539.76
27           1975      340758       1959               574.89
28           1975     1022888       3055               298.66
29           1975     2729878      14590               534.46
...           ...         ...        ...                  ...
2724         2015     1009176        606                60.05
2725         2015      658029       1847               280.69
2726         2015     1061175        555                52.30
2727         2015      393447       1497               380.48
2728         2015     8550861      16946               198.18
2729         2015      279110       1793               642.40
2730         2015      419481       3290               784.30
2731         2015      630621       1192               189.02
2732         2015      452252        655               144.83
2733         2015      268438        522               194.46
2734         2015     1567810       6765               431.49
2735         2015     1559744       3020               193.62
2736         2015      306870        858               279.60
2737         2015      685191       1359               198.34
2738         2015      438363        678               154.67
2739         2015      489717       1174               239.73
2740         2015      191992        469               244.28
2741         2015     1463586       1986               135.69
2742         2015     1400467       1378                98.40
2743         2015      863782       3610               417.93
2744         2015     1031458       1140               110.52
2745         2015      683700       1532               224.07
2746         2015      317095       1790               564.50
2747         2015     1341453        677                50.47
2748         2015      364383        671               184.15
2749         2015      529675       1059               199.93
2750         2015      401520        854               212.69
2751         2015      452797        270                59.63
2752         2015      672228       3404               506.38
2753         2015      389824        733               188.03

[2754 rows x 4 columns]

In [43]:
dataset.corr()

report_year  population  robberies  robberies_percapita
report_year             1.000000    0.065467  -0.096275            -0.231257
population              0.065467    1.000000   0.805544             0.097596
robberies              -0.096275    0.805544   1.000000             0.412895
robberies_percapita    -0.231257    0.097596   0.412895             1.000000

In [44]:
x=dataset.iloc[:,:3].values

In [45]:
x

array([[  1975, 286238,    819],
       [  1975, 112478,    113],
       [  1975, 490584,   3887],
       ..., 
       [  2015, 452797,    270],
       [  2015, 672228,   3404],
       [  2015, 389824,    733]])

In [46]:
y=dataset.iloc[:,3:].values

In [47]:
y

array([[ 286.13],
       [ 100.46],
       [ 792.32],
       ..., 
       [  59.63],
       [ 506.38],
       [ 188.03]])

In [48]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [49]:
x_train

array([[  2014, 450687,    305],
       [  1993, 732968,  12376],
       [  1994, 556724,   4245],
       ..., 
       [  1999, 347072,   1581],
       [  2013, 190246,    421],
       [  2015, 452252,    655]])

In [50]:
x_test

array([[   1980,  425122,     828],
       [   2010,  367635,     527],
       [   1990,  447619,    2801],
       ..., 
       [   1998,  593078,    2400],
       [   2001, 1246136,    1729],
       [   2013,  478182,    1158]])

In [51]:
y_train

array([[   67.67],
       [ 1688.48],
       [  762.5 ],
       ..., 
       [  455.53],
       [  221.29],
       [  144.83]])

In [52]:
y_test

array([[  194.77],
       [  143.35],
       [  625.76],
       [  292.45],
       [  359.75],
       [  278.43],
       [  689.48],
       [  341.  ],
       [  271.59],
       [  422.6 ],
       [  849.66],
       [  381.39],
       [  175.45],
       [   69.91],
       [  683.55],
       [  492.15],
       [  400.98],
       [  626.96],
       [  505.37],
       [  271.38],
       [  542.82],
       [  535.57],
       [  339.57],
       [  511.25],
       [   88.44],
       [  155.83],
       [  233.26],
       [  240.91],
       [  125.8 ],
       [  131.78],
       [  380.48],
       [  747.77],
       [  714.58],
       [  685.9 ],
       [  457.37],
       [ 1267.08],
       [  438.03],
       [ 1117.89],
       [  224.82],
       [   66.78],
       [  415.38],
       [  117.42],
       [  902.61],
       [  143.6 ],
       [  703.84],
       [  341.96],
       [  125.76],
       [  386.12],
       [  229.46],
       [  173.39],
       [  539.51],
       [  535.56],
       [  53

In [53]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [54]:
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [55]:
y_predict=lr.predict(x_train)

In [56]:
y_predict

array([[ 346.6421104 ],
       [ 770.42988004],
       [ 522.26267389],
       ..., 
       [ 457.80903518],
       [ 407.06675612],
       [ 355.37297889]])

In [57]:
lr.predict(np.array([[2020,389824,733]]))

array([[ 355.59219449]])

In [59]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

In [60]:
wml_credentials={
 "access_key": "GgZMM32w1gLCtS8RA-UPfDNV2LfBsJpclmZjjXArc0b5",
"instance_id": "0fdeecd1-1c61-498e-a787-eea2a1bcb465",
  "password": "0035d828-7b3e-4565-adc9-0facb6d8bea5",
  "url": "https://eu-gb.ml.cloud.ibm.com",
  "username": "23d328d7-25ab-439d-ada5-8a61e825e51c"
}

In [61]:
client=WatsonMachineLearningAPIClient(wml_credentials)

In [64]:
model_props={client.repository.ModelMetaNames.AUTHOR_NAME:"IBM",
             client.repository.ModelMetaNames.AUTHOR_EMAIL:"ibm@ibm.com",
            client.repository.ModelMetaNames.NAME:"Linear regression"}

In [65]:
model_artifact=client.repository.store_model(lr,meta_props=model_props)

In [66]:
published_model_uid=client.repository.get_model_uid(model_artifact)

In [67]:
created_deployment=client.deployments.create(published_model_uid,name="Linear regression")



#######################################################################################

Synchronous deployment creation for uid: '6a56b44b-e29a-42cc-ab7e-4f09a5aa3241' started

#######################################################################################


INITIALIZING
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='6006b67f-97c5-4ebc-9383-f755eae093b1'
------------------------------------------------------------------------------------------------




In [68]:
scoring_endpoint=client.deployments.get_scoring_url(created_deployment)

In [69]:
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/0fdeecd1-1c61-498e-a787-eea2a1bcb465/deployments/6006b67f-97c5-4ebc-9383-f755eae093b1/online'